version: "3.5"

services:
    db:
      restart: "no"
      ports:
          - "3306:3306"

    adminer:
      restart: "no"
      ports:
        - "8080:8080"

    backend:
      restart: "no"
      ports:
        - "8888:8888"
      volumes:
        - ./backend:/opt/backend
      build:
        context: ./backend
        args:
          INSTALL_DEV: ${INSTALL_DEV-true}

    frontend:
      restart: "no"
      volumes:
        - ./frontend/src:/app/src
        - ./frontend/public:/app/public
      ports:
        - "3000:3000"
      build:
        context: ./frontend
        # args:
        #   - NODE_ENV=development
