version: "3.5"

services:
    db:
      container_name: flickpulse_db
      image: mariadb:latest
      restart: always
      networks:
          - default
      env_file:
          - .env
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      volumes:
        - mariadb_data:/Users/jeanmarie/Documents/repos/projets-perso/flickpulse/backend/db

    adminer:
      container_name: flickpulse_adminer
      image: adminer
      restart: always
      networks:
          - default
      depends_on:
          - db
      environment:
          - ADMINER_DESIGN=pepa-linha-dark

    backend:
      container_name: flickpulse_backend
      # command: ./scripts/init-db.sh
      build:
        context: .
        dockerfile: Dockerfile
        args:
          INSTALL_DEV: ${INSTALL_DEV-false}
      platform: linux/amd64 # Patch for M1 Mac
      restart: always
      networks:
        - default
      depends_on:
        - db
      env_file:
        - .env
      environment:
        - DOMAIN=${DOMAIN}
        - ENVIRONMENT=${ENVIRONMENT}
        - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
        - SECRET_KEY=${SECRET_KEY}
        - FIRST_SUPERUSER=${FIRST_SUPERUSER}
        - FIRST_SUPERUSER_PASSWORD=${FIRST_SUPERUSER_PASSWORD}
        - USERS_OPEN_REGISTRATION=${USERS_OPEN_REGISTRATION}
        - SMTP_HOST=${SMTP_HOST}
        - SMTP_USER=${SMTP_USER}
        - SMTP_PASSWORD=${SMTP_PASSWORD}
        - EMAILS_FROM_EMAIL=${EMAILS_FROM_EMAIL}
        - MYSQL_SERVER=db
        - MYSQL_PORT=${MYSQL_PORT}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

volumes:
  mariadb_data: